import type { INodeProperties } from 'n8n-workflow';

export const projectGroupOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['projectGroup'] } },
		options: [
			{ name: 'Assign', value: 'assign', action: 'Assign user or team to project group' },
			{ name: 'Create', value: 'create', action: 'Create a project group' },
			{ name: 'Delete', value: 'delete', action: 'Delete a project group' },
			{ name: 'Duplicate', value: 'duplicate', action: 'Duplicate a project group' },
			{ name: 'Get', value: 'get', action: 'Get a project group' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many project groups' },
			{ name: 'Unassign', value: 'unassign', action: 'Unassign user or team from project group' },
			{ name: 'Update', value: 'update', action: 'Update a project group' },
		],
		default: 'getMany',
	},
];

export const projectGroupFields: INodeProperties[] = [
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['projectGroup'],
				operation: ['create', 'getMany'],
			},
		},
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['projectGroup'], operation: ['create'] } },
	},
	{
		displayName: 'Group ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['projectGroup'],
				operation: ['get', 'delete', 'duplicate', 'update', 'assign', 'unassign'],
			},
		},
	},
	{
		displayName: 'Delete Strategy',
		name: 'deleteStrategy',
		type: 'options',
		options: [
			{ name: 'Ungroup Tasks and Materials', value: 'ungroup_tasks_and_materials' },
			{ name: 'Delete Tasks and Materials', value: 'delete_tasks_and_materials' },
			{ name: 'Delete Tasks, Materials and Unbilled Time Trackings', value: 'delete_tasks_materials_and_unbilled_timetrackings' },
		],
		required: true,
		default: 'ungroup_tasks_and_materials',
		displayOptions: { show: { resource: ['projectGroup'], operation: ['delete'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['projectGroup'], operation: ['getMany'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 100,
		displayOptions: {
			show: { resource: ['projectGroup'], operation: ['getMany'], returnAll: [false] },
		},
	},
	// ----------------------------------
	//         projectGroup: assign / unassign
	// ----------------------------------
	{
		displayName: 'Assignee Type',
		name: 'assigneeType',
		type: 'options',
		options: [
			{ name: 'User', value: 'user' },
			{ name: 'Team', value: 'team' },
		],
		required: true,
		default: 'user',
		displayOptions: { show: { resource: ['projectGroup'], operation: ['assign', 'unassign'] } },
	},
	{
		displayName: 'Assignee ID',
		name: 'assigneeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['projectGroup'], operation: ['assign', 'unassign'] } },
	},

	// ----------------------------------
	//         projectGroup: create
	// ----------------------------------
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['projectGroup'], operation: ['create'] } },
		options: [
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'options',
				options: [
					{ name: 'Teal', value: '#00B2B2' },
					{ name: 'Dark Teal', value: '#008A8C' },
					{ name: 'Brown', value: '#992600' },
					{ name: 'Orange', value: '#ED9E00' },
					{ name: 'Pink', value: '#D157D3' },
					{ name: 'Purple', value: '#A400B2' },
					{ name: 'Blue', value: '#0071F2' },
					{ name: 'Dark Blue', value: '#004DA6' },
					{ name: 'Grey Blue', value: '#64788F' },
					{ name: 'Silver', value: '#C0C0C4' },
					{ name: 'Grey', value: '#82828C' },
					{ name: 'Black', value: '#1A1C20' },
				],
				default: '#00B2B2',
			},
			{
				displayName: 'Billing Method',
				name: 'billing_method',
				type: 'options',
				options: [
					{ name: 'Time & Materials', value: 'time_and_materials' },
					{ name: 'Fixed Price', value: 'fixed_price' },
					{ name: 'Parent Fixed Price', value: 'parent_fixed_price' },
					{ name: 'Non-Billable', value: 'non_billable' },
				],
				default: 'time_and_materials',
			},
			{
				displayName: 'Fixed Price Amount',
				name: 'fixed_price_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Only allowed if billing method is fixed price',
			},
			{
				displayName: 'Fixed Price Currency',
				name: 'fixed_price_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'External Budget Amount',
				name: 'external_budget_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Budget amount. Only allowed if billing method is time & materials.',
			},
			{
				displayName: 'External Budget Currency',
				name: 'external_budget_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Internal Budget Amount',
				name: 'internal_budget_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Cost budget amount',
			},
			{
				displayName: 'Internal Budget Currency',
				name: 'internal_budget_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Start Date',
				name: 'start_date',
				type: 'dateTime',
				default: '',
			},
			{
				displayName: 'End Date',
				name: 'end_date',
				type: 'dateTime',
				default: '',
			},
		],
	},

	// ----------------------------------
	//         projectGroup: update
	// ----------------------------------
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['projectGroup'], operation: ['update'] } },
		options: [
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'options',
				options: [
					{ name: 'Teal', value: '#00B2B2' },
					{ name: 'Dark Teal', value: '#008A8C' },
					{ name: 'Brown', value: '#992600' },
					{ name: 'Orange', value: '#ED9E00' },
					{ name: 'Pink', value: '#D157D3' },
					{ name: 'Purple', value: '#A400B2' },
					{ name: 'Blue', value: '#0071F2' },
					{ name: 'Dark Blue', value: '#004DA6' },
					{ name: 'Grey Blue', value: '#64788F' },
					{ name: 'Silver', value: '#C0C0C4' },
					{ name: 'Grey', value: '#82828C' },
					{ name: 'Black', value: '#1A1C20' },
				],
				default: '#00B2B2',
			},
			{
				displayName: 'Billing Method',
				name: 'billing_method_value',
				type: 'options',
				options: [
					{ name: 'Time & Materials', value: 'time_and_materials' },
					{ name: 'Fixed Price', value: 'fixed_price' },
					{ name: 'Parent Fixed Price', value: 'parent_fixed_price' },
					{ name: 'Non-Billable', value: 'non_billable' },
				],
				default: 'time_and_materials',
			},
			{
				displayName: 'Billing Method Update Strategy',
				name: 'billing_method_update_strategy',
				type: 'options',
				options: [
					{ name: 'None', value: 'none' },
					{ name: 'Cascade', value: 'cascade' },
				],
				default: 'none',
				description: 'Whether to cascade billing method change to child tasks',
			},
			{
				displayName: 'Fixed Price Amount',
				name: 'fixed_price_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Only allowed if billing method is fixed price',
			},
			{
				displayName: 'Fixed Price Currency',
				name: 'fixed_price_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'External Budget Amount',
				name: 'external_budget_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Budget amount. Only allowed if billing method is time & materials.',
			},
			{
				displayName: 'External Budget Currency',
				name: 'external_budget_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Internal Budget Amount',
				name: 'internal_budget_amount',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Cost budget amount',
			},
			{
				displayName: 'Internal Budget Currency',
				name: 'internal_budget_currency',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				default: '',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Start Date',
				name: 'start_date',
				type: 'dateTime',
				default: '',
			},
			{
				displayName: 'End Date',
				name: 'end_date',
				type: 'dateTime',
				default: '',
			},
		],
	},
];
