import type { INodeProperties } from 'n8n-workflow';

export const webhookOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['webhook'] } },
		options: [
			{ name: 'Get Many', value: 'getMany', action: 'Get many webhooks' },
			{ name: 'Register', value: 'register', action: 'Register a webhook' },
			{ name: 'Unregister', value: 'unregister', action: 'Unregister a webhook' },
		],
		default: 'getMany',
	},
];

export const webhookFields: INodeProperties[] = [
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['webhook'], operation: ['register'] } },
		description: 'The webhook URL to register',
	},
	{
		displayName: 'Event Types',
		name: 'types',
		type: 'multiOptions',
		options: [
			{ name: 'Account Deactivated', value: 'account.deactivated' },
			{ name: 'Call Added', value: 'call.added' },
			{ name: 'Call Completed', value: 'call.completed' },
			{ name: 'Call Deleted', value: 'call.deleted' },
			{ name: 'Call Updated', value: 'call.updated' },
			{ name: 'Company Added', value: 'company.added' },
			{ name: 'Company Deactivated', value: 'company.deactivated' },
			{ name: 'Company Deleted', value: 'company.deleted' },
			{ name: 'Company Updated', value: 'company.updated' },
			{ name: 'Contact Added', value: 'contact.added' },
			{ name: 'Contact Deactivated', value: 'contact.deactivated' },
			{ name: 'Contact Deleted', value: 'contact.deleted' },
			{ name: 'Contact Linked to Company', value: 'contact.linkedToCompany' },
			{ name: 'Contact Unlinked from Company', value: 'contact.unlinkedFromCompany' },
			{ name: 'Contact Updated', value: 'contact.updated' },
			{ name: 'Credit Note Booked', value: 'creditNote.booked' },
			{ name: 'Deal Created', value: 'deal.created' },
			{ name: 'Deal Deleted', value: 'deal.deleted' },
			{ name: 'Deal Lost', value: 'deal.lost' },
			{ name: 'Deal Moved', value: 'deal.moved' },
			{ name: 'Deal Updated', value: 'deal.updated' },
			{ name: 'Deal Won', value: 'deal.won' },
			{ name: 'Event Created', value: 'event.created' },
			{ name: 'Event Deleted', value: 'event.deleted' },
			{ name: 'Event Updated', value: 'event.updated' },
			{ name: 'Invoice Booked', value: 'invoice.booked' },
			{ name: 'Invoice Deleted', value: 'invoice.deleted' },
			{ name: 'Invoice Drafted', value: 'invoice.drafted' },
			{ name: 'Invoice Payment Registered', value: 'invoice.paymentRegistered' },
			{ name: 'Invoice Payment Removed', value: 'invoice.paymentRemoved' },
			{ name: 'Invoice Sent', value: 'invoice.sent' },
			{ name: 'Invoice Updated', value: 'invoice.updated' },
			{ name: 'Meeting Created', value: 'meeting.created' },
			{ name: 'Meeting Deleted', value: 'meeting.deleted' },
			{ name: 'Meeting Updated', value: 'meeting.updated' },
			{ name: 'Milestone Created', value: 'milestone.created' },
			{ name: 'Milestone Updated', value: 'milestone.updated' },
			{ name: 'Note Added', value: 'note.added' },
			{ name: 'Note Deleted', value: 'note.deleted' },
			{ name: 'Project Created', value: 'project.created' },
			{ name: 'Project Closed', value: 'project.closed' },
			{ name: 'Project Deleted', value: 'project.deleted' },
			{ name: 'Project Updated', value: 'project.updated' },
			{ name: 'Subscription Added', value: 'subscription.added' },
			{ name: 'Subscription Deactivated', value: 'subscription.deactivated' },
			{ name: 'Subscription Updated', value: 'subscription.updated' },
			{ name: 'Task Completed', value: 'task.completed' },
			{ name: 'Task Created', value: 'task.created' },
			{ name: 'Task Deleted', value: 'task.deleted' },
			{ name: 'Task Updated', value: 'task.updated' },
			{ name: 'Ticket Created', value: 'ticket.created' },
			{ name: 'Ticket Updated', value: 'ticket.updated' },
			{ name: 'Time Tracking Added', value: 'timeTracking.added' },
			{ name: 'Time Tracking Deleted', value: 'timeTracking.deleted' },
			{ name: 'Time Tracking Updated', value: 'timeTracking.updated' },
		],
		required: true,
		default: [],
		displayOptions: { show: { resource: ['webhook'], operation: ['register'] } },
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['webhook'], operation: ['unregister'] } },
		description: 'The webhook URL to unregister',
	},
	{
		displayName: 'Event Types',
		name: 'types',
		type: 'multiOptions',
		options: [
			{ name: 'Account Deactivated', value: 'account.deactivated' },
			{ name: 'Call Added', value: 'call.added' },
			{ name: 'Call Completed', value: 'call.completed' },
			{ name: 'Call Deleted', value: 'call.deleted' },
			{ name: 'Call Updated', value: 'call.updated' },
			{ name: 'Company Added', value: 'company.added' },
			{ name: 'Company Deactivated', value: 'company.deactivated' },
			{ name: 'Company Deleted', value: 'company.deleted' },
			{ name: 'Company Updated', value: 'company.updated' },
			{ name: 'Contact Added', value: 'contact.added' },
			{ name: 'Contact Deactivated', value: 'contact.deactivated' },
			{ name: 'Contact Deleted', value: 'contact.deleted' },
			{ name: 'Contact Linked to Company', value: 'contact.linkedToCompany' },
			{ name: 'Contact Unlinked from Company', value: 'contact.unlinkedFromCompany' },
			{ name: 'Contact Updated', value: 'contact.updated' },
			{ name: 'Credit Note Booked', value: 'creditNote.booked' },
			{ name: 'Deal Created', value: 'deal.created' },
			{ name: 'Deal Deleted', value: 'deal.deleted' },
			{ name: 'Deal Lost', value: 'deal.lost' },
			{ name: 'Deal Moved', value: 'deal.moved' },
			{ name: 'Deal Updated', value: 'deal.updated' },
			{ name: 'Deal Won', value: 'deal.won' },
			{ name: 'Event Created', value: 'event.created' },
			{ name: 'Event Deleted', value: 'event.deleted' },
			{ name: 'Event Updated', value: 'event.updated' },
			{ name: 'Invoice Booked', value: 'invoice.booked' },
			{ name: 'Invoice Deleted', value: 'invoice.deleted' },
			{ name: 'Invoice Drafted', value: 'invoice.drafted' },
			{ name: 'Invoice Payment Registered', value: 'invoice.paymentRegistered' },
			{ name: 'Invoice Payment Removed', value: 'invoice.paymentRemoved' },
			{ name: 'Invoice Sent', value: 'invoice.sent' },
			{ name: 'Invoice Updated', value: 'invoice.updated' },
			{ name: 'Meeting Created', value: 'meeting.created' },
			{ name: 'Meeting Deleted', value: 'meeting.deleted' },
			{ name: 'Meeting Updated', value: 'meeting.updated' },
			{ name: 'Milestone Created', value: 'milestone.created' },
			{ name: 'Milestone Updated', value: 'milestone.updated' },
			{ name: 'Note Added', value: 'note.added' },
			{ name: 'Note Deleted', value: 'note.deleted' },
			{ name: 'Project Created', value: 'project.created' },
			{ name: 'Project Closed', value: 'project.closed' },
			{ name: 'Project Deleted', value: 'project.deleted' },
			{ name: 'Project Updated', value: 'project.updated' },
			{ name: 'Subscription Added', value: 'subscription.added' },
			{ name: 'Subscription Deactivated', value: 'subscription.deactivated' },
			{ name: 'Subscription Updated', value: 'subscription.updated' },
			{ name: 'Task Completed', value: 'task.completed' },
			{ name: 'Task Created', value: 'task.created' },
			{ name: 'Task Deleted', value: 'task.deleted' },
			{ name: 'Task Updated', value: 'task.updated' },
			{ name: 'Ticket Created', value: 'ticket.created' },
			{ name: 'Ticket Updated', value: 'ticket.updated' },
			{ name: 'Time Tracking Added', value: 'timeTracking.added' },
			{ name: 'Time Tracking Deleted', value: 'timeTracking.deleted' },
			{ name: 'Time Tracking Updated', value: 'timeTracking.updated' },
		],
		required: true,
		default: [],
		displayOptions: { show: { resource: ['webhook'], operation: ['unregister'] } },
		description: 'The event types to unregister',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['webhook'], operation: ['getMany'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 20,
		displayOptions: {
			show: { resource: ['webhook'], operation: ['getMany'], returnAll: [false] },
		},
	},
];
